/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardRoomsRouteImport } from './routes/_dashboard.rooms'
import { Route as DashboardIngestionRouteImport } from './routes/_dashboard.ingestion'
import { Route as DashboardFacultyRouteImport } from './routes/_dashboard.faculty'
import { Route as DashboardDepartmentsRouteImport } from './routes/_dashboard.departments'
import { Route as DashboardCoursesRouteImport } from './routes/_dashboard.courses'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoomsRoute = DashboardRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIngestionRoute = DashboardIngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFacultyRoute = DashboardFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDepartmentsRoute = DashboardDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/courses': typeof DashboardCoursesRoute
  '/departments': typeof DashboardDepartmentsRoute
  '/faculty': typeof DashboardFacultyRoute
  '/ingestion': typeof DashboardIngestionRoute
  '/rooms': typeof DashboardRoomsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/courses': typeof DashboardCoursesRoute
  '/departments': typeof DashboardDepartmentsRoute
  '/faculty': typeof DashboardFacultyRoute
  '/ingestion': typeof DashboardIngestionRoute
  '/rooms': typeof DashboardRoomsRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/courses': typeof DashboardCoursesRoute
  '/_dashboard/departments': typeof DashboardDepartmentsRoute
  '/_dashboard/faculty': typeof DashboardFacultyRoute
  '/_dashboard/ingestion': typeof DashboardIngestionRoute
  '/_dashboard/rooms': typeof DashboardRoomsRoute
  '/_dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/courses'
    | '/departments'
    | '/faculty'
    | '/ingestion'
    | '/rooms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/courses'
    | '/departments'
    | '/faculty'
    | '/ingestion'
    | '/rooms'
    | '/'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/courses'
    | '/_dashboard/departments'
    | '/_dashboard/faculty'
    | '/_dashboard/ingestion'
    | '/_dashboard/rooms'
    | '/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/rooms': {
      id: '/_dashboard/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof DashboardRoomsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ingestion': {
      id: '/_dashboard/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof DashboardIngestionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/faculty': {
      id: '/_dashboard/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof DashboardFacultyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/departments': {
      id: '/_dashboard/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DashboardDepartmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/courses': {
      id: '/_dashboard/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardDepartmentsRoute: typeof DashboardDepartmentsRoute
  DashboardFacultyRoute: typeof DashboardFacultyRoute
  DashboardIngestionRoute: typeof DashboardIngestionRoute
  DashboardRoomsRoute: typeof DashboardRoomsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardDepartmentsRoute: DashboardDepartmentsRoute,
  DashboardFacultyRoute: DashboardFacultyRoute,
  DashboardIngestionRoute: DashboardIngestionRoute,
  DashboardRoomsRoute: DashboardRoomsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
